### PR TITLE
Making pylock work with Python3

### PR DESCRIPTION
**Pull request by zuzelvp**

### CODE REVIEW

**Comment by zuzelvp** [comment]
@nduthoit @nickpresta Hi. CR please.

**Comment by mwarkentin** [comment]
We should get this set up on travis so we can test across various versions.

**Comment by nduthoit** [comment]
LGTM thanks @zuzelvp

**Comment by JBKahn** [comment]
@zuzelvp I wrote a similar PR but added tox for testing: https://github.com/waveaccounting/pylock/pull/4

**Comment by JBKahn** [comment]
closed by https://github.com/waveaccounting/pylock/pull/4

**Pull request closed without merging**
